services:
  docs:
    image: accessrequestsapi_local_docs
    container_name: accessrequestsapi_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./accessrequestsapi:/app/accessrequestsapi:z
    ports:
      - '9000:9000'
    command: /start-docs
