volumes:
  accessrequestsapi_local_postgres_data: {}
  accessrequestsapi_local_postgres_data_backups: {}


services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: accessrequestsapi_local_django
    container_name: accessrequestsapi_local_django
    depends_on:
      - postgres
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    image: postgres:16-alpine
    container_name: accessrequestsapi_local_postgres
    volumes:
      - accessrequestsapi_local_postgres_data:/var/lib/postgresql/data
      - accessrequestsapi_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
